# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hattblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('center_lon', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('geometry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OKXECoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('value', models.FloatField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transform.Hattblock')),
            ],
        ),
    ]
