# Generated by Django 4.0.3 on 2022-04-16 12:58

from django.db import migrations, models
import os, json

def fill_okxe_ids(apps, schema_editor):
	Hattblock = apps.get_model("transform", "Hattblock")
	cur_dir = os.path.dirname(__file__) #/migrations
	transform_dir = os.path.split(cur_dir)[0] #/transform

	with open(os.path.join(transform_dir, 'hatt', 'hattblocks15.json'),'r', encoding="utf8") as fd:
		for chunk in json.load(fd):
			hb = Hattblock.objects.get(id=chunk['id'])
			hb.okxe_id = chunk['okxe_id']
			hb.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0002_load_hattblocks15'),
    ]

    operations = [
        migrations.AddField(
            model_name='hattblock',
            name='okxe_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
		migrations.RunPython(fill_okxe_ids)
    ]

